import { z } from "zod";

/**
 * A board is a read-only web status page per project (served by the harness at /board/<name>).
 * Agents write authored boards with the `update_board` MCP tool; `team` is generated by the harness.
 * Limits keep one agent from filling the disk or the browser: ~1 MB request cap applies on top.
 */

export const BoardStatus = z.enum(["done", "active", "blocked", "todo", "info"]);
export type BoardStatus = z.infer<typeof BoardStatus>;

/** Proof tier of a claim: runtime 🟢 · compile 🟡 · static 🟠 · none ⚪. */
export const ProofTier = z.enum(["runtime", "compile", "static", "none"]);
export type ProofTier = z.infer<typeof ProofTier>;

export const BOARD_LIMITS = {
  columns: 12,
  cardsPerColumn: 50,
  cardsTotal: 200,
  kpis: 12,
  edges: 300,
  tags: 8,
  outOfScope: 30,
  title: 120,
  text: 2000,
  short: 60,
} as const;

/** Reserved: the team board is generated from sessions + events, never stored. */
export const TEAM_BOARD = "team";
/** Generated from the project's plan markdown file — unless an agent wrote a board with this name (authored wins). */
export const PLAN_BOARD = "plan";

/**
 * What a board is for. Each kind has a documented layout recipe (docs/agent-guide.md §5.3) so every
 * agent draws, e.g., a release board the same way. `custom` = anything else.
 */
export const BoardKind = z.enum(["plan", "release", "review", "debug", "handoff", "custom"]);
export type BoardKind = z.infer<typeof BoardKind>;

export const BoardName = z
  .string()
  .regex(/^[a-z0-9][a-z0-9-]{0,39}$/, 'board name: lowercase letters, digits and "-" only, 1-40 chars, e.g. "plan" or "release-1"');

const Id = z.string().regex(/^[A-Za-z0-9_-]{1,64}$/, 'id: letters, digits, "_" or "-" only, 1-64 chars');
const Title = z.string().min(1).max(BOARD_LIMITS.title);
const Text = z.string().max(BOARD_LIMITS.text);
const Short = z.string().min(1).max(BOARD_LIMITS.short);

export const BoardCard = z.object({
  id: Id.describe("unique on this board; edges refer to it"),
  title: Title,
  body: Text.optional(),
  status: BoardStatus,
  tier: ProofTier.optional().describe("how the claim on this card was proven"),
  tags: z.array(Short).max(BOARD_LIMITS.tags).optional(),
});
export type BoardCard = z.infer<typeof BoardCard>;

export const BoardColumn = z.object({
  id: Id,
  title: Title,
  cards: z.array(BoardCard).max(BOARD_LIMITS.cardsPerColumn),
});
export type BoardColumn = z.infer<typeof BoardColumn>;

export const BoardEdge = z.object({
  from: Id.describe("card id"),
  to: Id.describe("card id"),
  style: z.enum(["solid", "dashed", "dotted"]).default("solid").describe("solid = main flow · dashed = back/pending · dotted = reference"),
  label: Short.optional(),
});
export type BoardEdge = z.infer<typeof BoardEdge>;

export const BoardKpi = z.object({
  label: Short,
  value: z.string().min(1).max(40),
  hint: z.string().max(BOARD_LIMITS.title).optional(),
  status: BoardStatus.optional(),
});
export type BoardKpi = z.infer<typeof BoardKpi>;

/** What an agent sends to `update_board` — name, updatedAt and updatedBy are added by the harness. */
export const BoardContent = z
  .object({
    kind: BoardKind.optional().describe('plan | release | review | debug | handoff | custom — layout recipe: guide("board <kind>")'),
    title: Title,
    subtitle: z.string().max(300).optional(),
    banner: z.object({ text: z.string().min(1).max(500), status: BoardStatus }).optional(),
    kpis: z.array(BoardKpi).max(BOARD_LIMITS.kpis).default([]),
    columns: z.array(BoardColumn).min(1).max(BOARD_LIMITS.columns),
    edges: z.array(BoardEdge).max(BOARD_LIMITS.edges).default([]),
    outOfScope: z.array(z.string().min(1).max(300)).max(BOARD_LIMITS.outOfScope).optional(),
  })
  .superRefine((b, ctx) => {
    const ids = new Set<string>();
    let total = 0;
    for (const col of b.columns) {
      for (const card of col.cards) {
        total++;
        if (ids.has(card.id)) ctx.addIssue({ code: "custom", message: `duplicate card id "${card.id}" — card ids must be unique on the board` });
        ids.add(card.id);
      }
    }
    // The one kind rule that matters at a glance: a release board must say whether it can ship.
    if (b.kind === "release" && !/^(GO|NO-GO)(?![\w-])/.test(b.banner?.text ?? "")) {
      ctx.addIssue({ code: "custom", message: 'release board: banner.text must start with "GO" or "NO-GO", e.g. { "text": "NO-GO — 2 checks failing", "status": "blocked" }' });
    }
    if (total > BOARD_LIMITS.cardsTotal) ctx.addIssue({ code: "custom", message: `too many cards (${total} > ${BOARD_LIMITS.cardsTotal}) — split into several boards` });
    for (const e of b.edges) {
      for (const end of [e.from, e.to]) {
        if (!ids.has(end)) ctx.addIssue({ code: "custom", message: `edge ${e.from} → ${e.to}: no card with id "${end}"` });
      }
    }
  });
export type BoardContent = z.infer<typeof BoardContent>;

export const Board = z.object({
  name: BoardName,
  updatedAt: z.number(), // ms since epoch, from the harness clock
  updatedBy: z.string().optional(), // role, from the writer's session token
}).and(BoardContent);
export type Board = z.infer<typeof Board>;

/** One row of the board list (/board.json). source: generated = team · file = plan markdown · agent = update_board. */
export const BoardSummary = z.object({
  name: BoardName,
  title: z.string(),
  kind: BoardKind.optional(),
  source: z.enum(["generated", "file", "agent"]),
  updatedAt: z.number(),
  updatedBy: z.string().optional(),
});
export type BoardSummary = z.infer<typeof BoardSummary>;

/** Where the running harness serves boards; written 0600 to .crewmux/state so the sidebar can show it. */
export const BoardView = z.object({ runId: z.string(), origin: z.string(), token: z.string() });
export type BoardView = z.infer<typeof BoardView>;

export const boardUrl = (view: Pick<BoardView, "origin" | "token">, name: string = TEAM_BOARD): string =>
  `${view.origin}/board/${name}?t=${view.token}`;

/** The page that lists every board of the project. */
export const boardListUrl = (view: Pick<BoardView, "origin" | "token">): string => `${view.origin}/board?t=${view.token}`;
