import { existsSync, readFileSync, realpathSync } from "node:fs";
import { isAbsolute, relative, resolve } from "node:path";
import { z } from "zod";
import { ArtifactKind, BoardContent, BoardName, MessageType, newId, PLAN_BOARD, ReviewVerdict, TEAM_BOARD, USER, type AgentEnvelope, type Board, type BoardSummary } from "../protocol/index.js";
import type { EventBus } from "../core/event-bus.js";
import type { PathPolicy } from "../core/policy-engine.js";
import type { SessionRegistry } from "../core/session-registry.js";
import { writeArtifact } from "../workspace/artifacts.js";
import { loadSections, searchSections } from "./guide.js";

/**
 * Who is calling. Derived ONLY from the bearer token the harness issued for this
 * agent session — never from tool arguments, so an agent cannot impersonate another.
 */
export interface CallerIdentity {
  runId: string;
  sessionId: string;
  role: string;
  agentId: string;
  cwd: string;
}

/**
 * Boards as the bridge sees them. Injected by runtime (which owns storage and generates the team
 * board), so bridge never touches files or sessions-to-board logic itself.
 */
export interface BoardAccess {
  /** Random per harness run; browsers send it as ?t= because they cannot send the MCP bearer. */
  viewToken: string;
  /** The board web page (templates/board.html). */
  page: () => string;
  /** An authored board, or the generated "team" board. undefined = unknown name. */
  get: (name: string) => Board | undefined;
  list: () => BoardSummary[];
  put: (board: Board) => void;
}

export interface BridgeDeps {
  bus: EventBus;
  sessions: SessionRegistry;
  policy: PathPolicy;
  agentDir: string;
  /** Latest known context size of a role (runtime reads it from the CLI's session files). */
  usage?: (role: string) => { tokens: number; window?: number } | undefined;
  /** Type the CLI's compact command into a role's session. Throws ToolError when not allowed. */
  compact?: (by: string, target: string, focus: string) => Promise<void>;
  boards?: BoardAccess;
  /** Clock for timestamps the bridge sets itself (board updatedAt). Default Date.now. */
  now?: () => number;
}

export class ToolError extends Error {}

/** Input schemas (zod raw shapes) — shared by the MCP server and by tests. */
export const TOOL_INPUTS = {
  list_agents: {},
  send_message: {
    to: z.string().describe('Recipient role (see list_agents), or "user" for the human'),
    type: MessageType.exclude(["review_result"]).default("request"),
    content: z.string().min(1),
    artifacts: z.array(z.string()).default([]).describe("Artifact ids to attach (from report_artifact)"),
    replyTo: z.string().optional().describe("Message id you are answering"),
  },
  submit_review: {
    to: z.string().describe("Role whose work you reviewed"),
    verdict: ReviewVerdict,
    notes: z.string().min(1).describe("Findings, tagged [BLOCKER]/[MAJOR]/[MINOR] with file:line"),
    replyTo: z.string().optional(),
  },
  report_artifact: {
    kind: ArtifactKind,
    path: z.string().describe("Path relative to your working directory"),
    summary: z.string().default(""),
  },
  ask_user: {
    question: z.string().min(1),
  },
  compact: {
    target: z.string().optional().describe("Role to compact; omit for yourself"),
    focus: z.string().default("").describe("What the summary must keep: decisions, file paths, open TODOs, pending message ids"),
  },
  update_board: {
    name: BoardName.describe('Board to create or replace, e.g. "plan". "team" is reserved (generated by the harness).'),
    board: BoardContent.describe("Full board content — replaces the previous version"),
  },
  guide: {
    topic: z.string().default("").describe('What the user wants, e.g. "add grok", "bypass permissions", "resume", "keys". Empty = list all topics.'),
  },
} as const;

export const TOOL_DESCRIPTIONS: Record<keyof typeof TOOL_INPUTS, string> = {
  list_agents: "Who you are and which other agent roles are running right now.",
  send_message: "Send a message to another agent role (or the user). It is typed into that agent's session. Never contact agents any other way.",
  submit_review: "Send your review verdict to the role whose work you reviewed.",
  report_artifact: "Register a file you produced (diff, test report, analysis, ...) so you can attach it to a message by id.",
  ask_user: "Ask the human a question. The answer arrives later as normal input; end your turn after asking.",
  compact:
    "Compact an agent's conversation (yours by default) to save tokens. It runs after the target's current turn. " +
    "Use at task boundaries — after a task is finished and reported, before unrelated new work, after reading long logs/diffs — " +
    "never mid-task or while you wait for an answer that needs the details. Put what must survive in `focus`.",
  update_board:
    "Create or replace a status board the human watches in a browser (Ctrl-b B): banner, KPI tiles, columns of cards " +
    "with status done|active|blocked|todo|info and proof tier runtime|compile|static|none, edges between cards, out-of-scope list. " +
    "Send the whole board each time. Use it for plans, progress and verification status; keep cards short. " +
    'Set `kind` (plan|release|review|debug|handoff|custom) and follow its layout from guide("board <kind>"); a release banner starts with GO or NO-GO.',
  guide:
    "The crewmux manual. Call it BEFORE answering any question about using or configuring crewmux " +
    "(roles, adding a CLI such as grok, models, bypass/permissions, resume, keys, troubleshooting) or editing .crewmux/. " +
    "Then walk the user through the returned steps (or do them if asked) — do not tell them to go read docs.",
};

type Inputs = { [K in keyof typeof TOOL_INPUTS]: z.infer<z.ZodObject<(typeof TOOL_INPUTS)[K]>> };

/** Transport-independent tool logic. The MCP server is a thin wrapper around this. */
export function createToolHandlers(deps: BridgeDeps, caller: CallerIdentity) {
  const route = (to: string, type: AgentEnvelope["type"], content: string, extra: Partial<AgentEnvelope> = {}) => {
    if (to === caller.role) throw new ToolError("cannot send a message to yourself");
    if (to !== USER && !deps.sessions.byRole(to)) {
      const live = deps.sessions.list().filter((s) => s.status !== "exited").map((s) => s.role);
      throw new ToolError(`no running agent with role "${to}" (running: ${live.join(", ") || "none"})`);
    }
    const envelope: AgentEnvelope = { id: newId("msg"), from: caller.role, to, type, content, artifacts: [], ...extra };
    deps.bus.publish({ type: "message", runId: caller.runId, envelope });
    return { messageId: envelope.id, status: "queued" as const };
  };

  const contextOf = (role: string) => {
    const u = deps.usage?.(role);
    if (!u) return "unknown";
    return u.window ? `${u.tokens} tokens (${Math.round((u.tokens / u.window) * 100)}% of ${u.window})` : `${u.tokens} tokens`;
  };

  return {
    list_agents(_: Inputs["list_agents"]) {
      return {
        you: { role: caller.role, agentId: caller.agentId },
        yourContext: contextOf(caller.role),
        peers: deps.sessions
          .list()
          .filter((s) => s.status !== "exited" && s.id !== caller.sessionId)
          .map((s) => ({ role: s.role, agentId: s.agentId, kind: s.kind, status: s.status, context: contextOf(s.role) })),
      };
    },

    send_message(input: Inputs["send_message"]) {
      return route(input.to, input.type, input.content, { artifacts: input.artifacts, ...(input.replyTo ? { replyTo: input.replyTo } : {}) });
    },

    submit_review(input: Inputs["submit_review"]) {
      return route(input.to, "review_result", input.notes, { verdict: input.verdict, ...(input.replyTo ? { replyTo: input.replyTo } : {}) });
    },

    report_artifact(input: Inputs["report_artifact"]) {
      if (isAbsolute(input.path)) throw new ToolError("path must be relative to your working directory");
      const abs = resolve(caller.cwd, input.path);
      if (!existsSync(abs)) throw new ToolError(`file not found: ${input.path}`);
      // Resolve symlinks before the containment check so a link can't escape the working directory.
      const rel = relative(realpathSync(caller.cwd), realpathSync(abs));
      if (rel.startsWith("..") || isAbsolute(rel)) throw new ToolError("path escapes your working directory");
      const verdict = deps.policy.check(rel);
      if (!verdict.allowed) throw new ToolError(`denied by policy (${verdict.rule})`);

      const ref = writeArtifact(deps.agentDir, caller.runId, caller.sessionId, caller.role, input.kind, readFileSync(abs, "utf8"), {
        source: rel,
        summary: input.summary,
      });
      deps.bus.publish({ type: "artifact.created", runId: caller.runId, artifact: ref });
      return { artifactId: ref.id };
    },

    ask_user(input: Inputs["ask_user"]) {
      return route(USER, "question", input.question);
    },

    async compact(input: Inputs["compact"]) {
      if (!deps.compact) throw new ToolError("compaction is not available in this harness");
      const target = input.target ?? caller.role;
      await deps.compact(caller.role, target, input.focus);
      return { target, status: "queued", note: "runs when the target's current turn ends" };
    },

    update_board(input: Inputs["update_board"]) {
      if (!deps.boards) throw new ToolError("boards are not available in this harness");
      if (input.name === TEAM_BOARD) {
        throw new ToolError(`board "${TEAM_BOARD}" is generated by the harness from sessions and messages — pick another name, e.g. "plan" or "status"`);
      }
      // updatedBy comes from the session token, updatedAt from the harness clock — never from arguments.
      const board: Board = { ...input.board, name: input.name, updatedAt: (deps.now ?? Date.now)(), updatedBy: caller.role };
      deps.boards.put(board);
      deps.bus.publish({ type: "board.updated", runId: caller.runId, name: input.name, by: caller.role });
      const note = `the human opens it with Ctrl-b B or \`crewmux board ${input.name}\``;
      return {
        name: input.name, status: "saved", path: `/board/${input.name}`,
        note: input.name === PLAN_BOARD
          ? `${note}. This authored "plan" now wins over the board generated from plan.md; delete .crewmux/state/boards/plan.json to go back to it`
          : note,
      };
    },

    guide(input: Inputs["guide"]) {
      const sections = loadSections();
      if (!input.topic.trim()) {
        return { topics: sections.map((s) => `[${s.doc}] ${s.title}`), hint: "call guide again with a topic to get the full steps" };
      }
      const hits = searchSections(sections, input.topic);
      if (!hits.length) return { found: 0, topics: sections.map((s) => `[${s.doc}] ${s.title}`) };
      return { found: hits.length, sections: hits.map((s) => ({ doc: s.doc, title: s.title, text: s.body })) };
    },
  };
}
